### ISSUE TITLE
binary for windows

### ISSUE THREAD

**Issue by ghost** [YaLTeR/compress#1]
can you release a binary for windows

**Comment by YaLTeR** [comment]
Sure, [here you go](https://github.com/YaLTeR/compress/releases/tag/v1.0), why do you need it though?

**Comment by ghost** [comment]
@YaLTeR https://encode.ru/threads/2953-Nanzip-compressed-2GB-to-95KB-!-How-is-it-even-possible
BWT is good at compressing wordlists
